# Generated by Django 5.2.13 on 2026-04-13 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        (
            "sessions_app",
            "0003_alter_sessionlog_options_remove_session_end_time_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SEARCH", "Search"),
                            ("BROWSE", "Browse"),
                            ("ENGAGEMENT", "Engagement"),
                            ("BOOKING", "Booking"),
                            ("CONTENT", "Content"),
                            ("FEEDBACK", "Feedback"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_events",
                        to="curriculum.contentresource",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_events",
                        to="sessions_app.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="ai_analytic_user_id_7a4663_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="ai_analytic_event_t_178d1f_idx",
                    ),
                    models.Index(
                        fields=["category", "created_at"],
                        name="ai_analytic_categor_eae3f2_idx",
                    ),
                ],
            },
        ),
    ]
