# Generated by Django 6.0.3 on 2026-04-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tutor_payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('awaiting_payment', 'Awaiting Payment'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(choices=[('parent', 'Parent'), ('tutor', 'Tutor'), ('system', 'System')], max_length=10)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('event_details', models.JSONField(default=dict)),
            ],
        ),
    ]
