# Generated by Django 6.0.3 on 2026-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
