# Generated by Django 5.2.13 on 2026-04-13 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
        ("sessions_app", "0002_initial"),
        ("users", "0002_remove_tutorprofile_account_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="session",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="session",
            name="platform_fee",
        ),
        migrations.RemoveField(
            model_name="session",
            name="scheduled_date",
        ),
        migrations.RemoveField(
            model_name="session",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="session",
            name="total_cost",
        ),
        migrations.RemoveField(
            model_name="session",
            name="tutor_payout_amount",
        ),
        migrations.RemoveField(
            model_name="sessionlog",
            name="event_details",
        ),
        migrations.AddField(
            model_name="session",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="subject_old",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sessionlog",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="session",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="duration_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="users.parentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="users.student",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="curriculum.subject",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="users.tutorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="sessionlog",
            name="actor_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sessionlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="sessionlog",
            name="status_after",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="sessionlog",
            name="status_before",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "student_performance",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("AVERAGE", "Average"),
                            ("BELOW_AVERAGE", "Below Average"),
                            ("STRUGGLING", "Struggling"),
                        ],
                        default="AVERAGE",
                        max_length=20,
                    ),
                ),
                ("strengths", models.TextField(blank=True, null=True)),
                ("areas_for_improvement", models.TextField(blank=True, null=True)),
                ("homework_assigned", models.TextField(blank=True, null=True)),
                (
                    "next_session_recommendations",
                    models.TextField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_note",
                        to="sessions_app.session",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_notes",
                        to="users.tutorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics_covered",
                        to="sessions_app.session",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_covering",
                        to="curriculum.curriculumtag",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "topic")},
            },
        ),
    ]
