# Generated by Django 6.0.3 on 2026-04-10 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_initial'),
        ('users', '0002_remove_tutorprofile_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='session',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='session',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tutor_payout_amount',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='event_details',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='status_after',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='status_before',
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.parentprofile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.tutorprofile'),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='actor_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
