# Generated by Django 6.0.3 on 2026-04-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='sessions_app.session'),
        ),
    ]
