# Generated by Django 5.2.13 on 2026-04-13 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_initial"),
        (
            "sessions_app",
            "0003_alter_sessionlog_options_remove_session_end_time_and_more",
        ),
        ("users", "0002_remove_tutorprofile_account_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispute",
            name="description",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="parent_refund_amount",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="raised_by_id",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="resolution_details",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="tutor_payment_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refund_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refunded_at",
        ),
        migrations.RemoveField(
            model_name="payout",
            name="bank_reference",
        ),
        migrations.RemoveField(
            model_name="payout",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="payout",
            name="released_at",
        ),
        migrations.AddField(
            model_name="dispute",
            name="category",
            field=models.CharField(
                choices=[
                    ("NO_SHOW", "No Show"),
                    ("SESSION_QUALITY", "Session Quality"),
                    ("SHORT_SESSION", "Short Session"),
                    ("WRONG_SUBJECT", "Wrong Subject"),
                    ("TUTOR_BEHAVIOUR", "Tutor Behaviour"),
                    ("PAYMENT_ISSUE", "Payment Issue"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="parent_refund",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="raised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes_raised",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="tutor_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="raised_by_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="reason",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute",
                to="sessions_app.session",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(default="paystack", max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_reference",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="sessions_app.session",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payout",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payout",
                to="sessions_app.session",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("PROCESSED", "Processed"),
                    ("FAILED", "Failed"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="users.tutorprofile",
            ),
        ),
    ]
